# -*- coding: utf-8 -*-
"""Welco_mdluli.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M_IYG4T9krJlvdbjsePI2Z2Jf7-84qB0
"""

#import neccesary libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from datetime import datetime as dt

#table1 data
data1=[['L2001','Welcome','Mdluli','M',26],['L2002','Ncobile','Shongwe','F',20],['L2003','Senzelwe','Dlamini','M',23],['L2004','Ernest','Matsenjwa','M',19],['L2005','Brian','Smith','M',20]]

#using pandas to give column names for the first table
df1=pd.DataFrame(data1, columns=['Userid','Username','Usersurname','Gender','Age'])

#creating a histogram for the numerical data for table 1
df1.hist()

df1.plot.bar()

# Count the number of males and females
num_males = len(df1[df1['Gender'] == 'M'])
num_females = len(df1[df1['Gender'] == 'F'])


# Create a histogram
plt.figure(figsize=(8, 6))
plt.bar(['Males', 'Females'], [num_males, num_females], color=['blue', 'pink'])
plt.xlabel('Gender')
plt.ylabel('Count')
plt.title('Distribution of Males and Females')
plt.show()

"""**The following is the second table**"""

# Given data (title, description, release date)
data2 = [['48 Laws of Power', 'Mindset', '2017-10-12'],
         ['Black Beauty', 'Romance', '2007-09-23'],
         ['Great Expectation', 'Mindset', '2014-03-03'],
         ['Marriage', 'Life', '2001-07-24'],
         ['Once Upon a Time', 'Education', '2019-06-30'],
         ['Richest Man', 'Economics', '2009-02-05']]

# Extract release years
release_years = [int(book[2][:4]) for book in data2]

# Create a DataFrame
df2 = pd.DataFrame({'Title': [book[0] for book in data2], 'ReleaseYear': release_years})

# Filter books based on release year intervals
df2_2000_2005 = df2[(df2['ReleaseYear'] >= 2000) & (df2['ReleaseYear'] <= 2005)]
df2_2006_2010 = df2[(df2['ReleaseYear'] >= 2006) & (df2['ReleaseYear'] <= 2010)]
df2_2011_2015 = df2[(df2['ReleaseYear'] >= 2011) & (df2['ReleaseYear'] <= 2015)]
df2_2016_2020 = df2[(df2['ReleaseYear'] >= 2016) & (df2['ReleaseYear'] <= 2020)]

# Plot the number of books released in each interval
plt.figure(figsize=(10, 6))
plt.bar(['2000-2005', '2006-2010', '2011-2015', '2016-2020'],
        [len(df2_2000_2005), len(df2_2006_2010), len(df2_2011_2015), len(df2_2016_2020)],
        color=['blue', 'green', 'orange', 'purple'])
plt.xlabel('Release Year Interval')
plt.ylabel('Number of Books')
plt.title('Number of Books Released in Different Intervals')
plt.show()

"""**The third table**"""

data3=[['Good','Skhandzisa','M','L2004'],['Lenhle','Maziya','F','L2002'],['Lihle','Dladla','M','L2003'],['Sethu','Methula','F','L2002'],['Sipho','Dladla','F','L2003']]

df3=pd.DataFrame(data3, columns=['librName','Librsurname','Gender','UID'])

# Count the number of males and females
num_males = len(df3[df3['Gender'] == 'M'])
num_females = len(df3[df3['Gender'] == 'F'])



# Create a histogram
plt.figure(figsize=(8, 6))
plt.bar(['Males', 'Females'], [num_males, num_females], color=['green', 'red'])
plt.xlabel('Gender')
plt.ylabel('Count')
plt.title('Library Distribution of Males and Females')
plt.show()